<?php
/**
 * @file
 * Code for the Educloud Alliance Portal configuration feature.
 */

include_once 'educloudalliance_portal_configuration.features.inc';
/**
 * @file
 * Module functions for configuration module.
 */

/**
 * Implements hook_menu().
 */
function educloudalliance_portal_configuration_menu() {

  $items['json/bazaar'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => '_serve_json',
    'page arguments' => array(1),
    'access callback' => TRUE,
  );

  $items['json/wishes'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => '_serve_json',
    'page arguments' => array(1),
    'access callback' => TRUE,
  );

  $items['json/qa'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => '_serve_json',
    'page arguments' => array(1),
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Return JSON out of predefined testing variables.
 */
function _serve_json($request) {
  $data = variable_get('frontpage_test_json_' . $request);
  if (empty($data)) {
    switch ($request) {
      case 'bazaar':
        $data = array(
          array('id' => 1, 'title' => 'Bazaar product 1'),
        );
        break;
      case 'wishes':
        $data =  array(
            array('postid' => 1, 'title' => 'Wish 1'),
            array('postid' => 2, 'title' => 'Wish 2'),
            array('postid' => 3, 'title' => 'Wish 3'),
        );

        break;
      case 'qa':
        $data = array(
            array('postid' => 1, 'title' => 'Question 1'),
            array('postid' => 2, 'title' => 'Question 2'),
            array('postid' => 3, 'title' => 'Question 3'),
        );
    }
    variable_set('frontpage_test_json_' . $request, $data);
  }
  return drupal_json_output($data);
}

/**
 * Implements hook_views_default_views_alter(). Fixes json uris for frontpage blocks.
 */
function educloudalliance_portal_configuration_views_default_views_alter(&$view) {
  $url = url('', array('absolute' => TRUE));
  $view['frontpage_feature_wishes']->display['default']->display_options['query']['options']['json_file'] = $url . '/json/wishes';
  $view['frontpage_qa']->display['default']->display_options['query']['options']['json_file'] = $url . '/json/qa';
  $view['frontpage_bazaar_items']->display['default']->display_options['query']['options']['json_file'] = $url . '/json/bazaar';
}

